# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [ ]:
np.__version__

'1.19.5'

#### 3. Create a null vector of size 10

In [ ]:
def nullvector(n):
  a= np.zeros(n)
  print(a)
nullvector(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [ ]:
import numpy as np
a = np.zeros(10)
print(a.size *a.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
def nullvector(n):
  a= np.zeros(n)
  a[4]=1
  print(a)
nullvector(10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [ ]:
def randomgen():
  a= 10 + np.random.random()*39
  print(a)
randomgen()

19.71643739680392


#### 8.  Reverse a vector (first element becomes last)

In [65]:
a = np.arange(10,50)
a= a[::-1]
print (a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
a= np.empty((3, 3), int)
for i in range(0,3):
  for j in range(0,3):
    a[i][j]= np.random.random()*9
print(a)

[[2 8 6]
 [2 6 7]
 [2 1 1]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
a=[1,2,0,0,4,0]
for i in range(0,6):
  if a[i]>0:
    print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [ ]:
a= np.identity(3, dtype=int)
print(a)
    

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values

In [18]:
a = np.empty((3,3,3),int)
for i in range(0,3):
  for j in range(0,3):
    for k in range(0,3):
      a[i][j][k]= np.random.random()*90
print(a)

[[[78 50 10]
  [10 44 23]
  [19 40 88]]

 [[21 27 77]
  [78 62 38]
  [ 1 22 82]]

 [[21 53 63]
  [ 4 43  4]
  [68 27 30]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
a= np.empty((10,10),int)
for i in range(0,10):
  for j in range(0,10):
    a[i][j]=10 + np.random.random()*90
print(a)
print(a.max())
print(a.min())

[[20 34 66 51 26 31 12 48 61 86]
 [90 92 97 59 61 11 72 63 93 73]
 [44 52 42 34 86 62 68 43 33 16]
 [46 74 26 27 28 61 27 55 92 60]
 [83 35 68 26 98 51 73 34 44 14]
 [74 85 33 82 28 13 96 17 53 69]
 [50 85 91 31 57 14 43 53 55 95]
 [63 71 80 15 38 94 60 85 32 68]
 [57 32 98 17 81 38 78 90 54 42]
 [41 41 98 76 41 93 27 42 76 57]]
98
11


#### 14. Create a random vector of size 30 and find the mean value

In [33]:
a=np.random.random(30)
print(a.mean())

0.44994961435778286


#### 15. Create a 2d array with 1 on the border and 0 inside

In [40]:
a=np.zeros((5,5),int)
for i in range(0,5):
  for j in range(0,5):
    if i==0 or i==4 or j==0 or j==4:
      a[i][j]=1 
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]




```
# This is formatted as code
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [64]:
a=np.zeros((5,5),int)
for i in range(0,5):
  for j in range(0,5):
    if i==0 or i==4 or j==0 or j==4:
      a[i][j]=1 
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [61]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [43]:
a=np.zeros((5,5),int)
k=1
for i in range(0,5):
  for j in range(0,5):
    if i==j:
      if k>4:
        break
      else:
        a[i+1][j]=k
        k=k+1
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

---



In [60]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [57]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
